### ISSUE TITLE
Set invokeApply to false to avoid unnecessary digest cycles

### ISSUE THREAD

**Issue by codef0rmer** [eu81273/angular.snackbar#1]
As you are not updating any scope variables in both the `$timeout` calls, you can avoid unnecessary digest loops with:
1. Use [a third parameter as `false`](https://docs.angularjs.org/api/ng/service/$timeout) in both the `$timeout` calls used.
2. Replace `$timeout` with `window.setTimeout` otherwise.

**Comment by eu81273** [comment]
I just think that $timeout returns "Promise". $timeout included digest loops? 

Is below right you suggest?

```
window.setTimeout(function () {

    angular.element(snackbar).removeClass("snackbar-opened");

    window.setTimeout( function () { element.remove(); }, snackbarRemoveDelay);

}, received.timeout || snackbarDuration);
```

**Comment by codef0rmer** [comment]
@eu81273: That's correct.

**Comment by eu81273** [comment]
@codef0rmer 
when replaced $timeout with window.setTimeout, snackbar was work something wrong way. appears only first time.. or not appeared

so I added $apply logics, but still wrong..

**Comment by codef0rmer** [comment]
@eu81273 : check the PR (https://github.com/eu81273/angular.snackbar/pull/2)

**Comment by eu81273** [comment]
One thing I have learned more, thanks. Thank you for your comment and pull.

$timeout(fn, [delay], [invokeApply]);
invokeApply / (optional) / boolean
If set to false skips model dirty checking, otherwise will invoke fn within the $apply block. (default: true)

**Comment by eu81273** [comment]
in your jsfiddle(http://jsfiddle.net/wtfdzehr/4/), if press create snackbar button 3~5 times quickly then snackbar remains like below.

![remains](https://cloud.githubusercontent.com/assets/2687916/5629647/239731c6-95f9-11e4-9d1b-3b472850d0a6.png)

**Comment by codef0rmer** [comment]
Fixed in https://github.com/eu81273/angular.snackbar/pull/3

**Comment by eu81273** [comment]
Thank you :smile:
